[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "onFailure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"